name: Create a commet on new issues

on:
  issues:
     type: [opened]
jobs:
  comment-with-action:
     runs-on: ubuntu-latest
     steps:
       - name: "dumb github context"
         run: echo '${{ toJSON(github.event) }}' | jq
         shell: bash
         
